### ISSUE TITLE
Python script error

### ISSUE THREAD

**Issue by hallux4** [ConSol/omd#102]
Hi,

Sorry for my bad English.

I am setting up a monitoring platform for my company (and later for each clients).
I began to work on a normal setup using Naemon in a docker container.
Everything is fine.

But then yesterday I learned about OMD (which looks really awesome).
So I imported my configuration, including a custom Python script for DingTalk notifications.

When I run it as normal user (nagios or root), everything is fine.
``` bash
sudo -u nagios /omd/sites/OMD_SITENAME/lib/monitoring-plugins/dingtalk2.py --url "https://oapi.dingtalk.com/robot/send?access_token=URL_TOKEN" \
                                    --notificationtype "$NOTIFICATIONTYPE$" \
                                    --hostalias "$HOSTNAME$" \
                                    --hostaddress "$HOSTADDRESS$" \
                                    --hoststate "$HOSTSTATE$" \
                                    --hostoutput "$HOSTOUTPUT$" \
                                    --cgiurl "https://URL_VPS/OMD_SITENAME/thruk/#cgi-bin/extinfo.cgi"
{"errcode":0,"errmsg":"ok"}
```

But when I start it from inside the OMD user.
I get this error.

``` bash
Traceback (most recent call last):
  File "/omd/sites/OMD_SITENAME/lib/python/requests-2.10.0-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 11, in <module>
    from queue import LifoQueue, Empty, Full
  File "/omd/sites/OMD_SITENAME/lib/python/future-0.16.0-py2.7.egg/queue/__init__.py", line 8, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/omd/sites/OMD_SITENAME/lib/python/requests-2.10.0-py2.7.egg/requests/packages/__init__.py", line 27, in <module>
    from . import urllib3
  File "/omd/sites/OMD_SITENAME/lib/python/requests-2.10.0-py2.7.egg/requests/packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/omd/sites/OMD_SITENAME/lib/python/requests-2.10.0-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 13, in <module>
    from Queue import LifoQueue, Empty, Full
ModuleNotFoundError: No module named 'Queue'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/omd/sites/OMD_SITENAME/lib/monitoring-plugins/dingtalk2.py", line 18, in <module>
    import requests
  File "/omd/sites/OMD_SITENAME/lib/python/requests-2.10.0-py2.7.egg/requests/__init__.py", line 61, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "/omd/sites/OMD_SITENAME/lib/python/requests-2.10.0-py2.7.egg/requests/packages/__init__.py", line 29, in <module>
    import urllib3
  File "/usr/lib/python3/dist-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/usr/lib/python3/dist-packages/urllib3/exceptions.py", line 2, in <module>
    from six.moves.http_client import (
  File "/omd/sites/OMD_SITENAME/lib/python/six-1.10.0-py2.7.egg/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/omd/sites/OMD_SITENAME/lib/python/six-1.10.0-py2.7.egg/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/omd/sites/OMD_SITENAME/lib/python/six-1.10.0-py2.7.egg/six.py", line 82, in _import_module
    __import__(name)
  File "/omd/sites/OMD_SITENAME/lib/python/future-0.16.0-py2.7.egg/http/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
```

Some information about the said script.
``` python
head /omd/sites/OMD_SITENAME/lib/monitoring-plugins/dingtalk2.py
#!/usr/bin/env python3
import argparse
import json
import requests

OMD[OMD_SITENAME@URL_VPS]:~$ python -V
Python 3.7.3

OMD[OMD_SITENAME@URL_VPS]:~$ ls -l /usr/bin/python
lrwxrwxrwx 1 root root 16 Jun 17 09:48 /usr/bin/python -> /usr/bin/python3*
lrwxrwxrwx 1 root root       9 Mar 26  2019 /usr/bin/python3 -> python3.7*
-rwxr-xr-x 2 root root 4877888 Dec 21  2019 /usr/bin/python3.7*
```

Are you able to tell if the problem come from my python setup or OMD ?

**Comment by hallux4** [comment]
This is the output of pip -V
``` python
OMD[OMD_SITENAME@URL_VPS]:~$ pip3 -V
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 6, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
    from pip._internal.cli.progress_bars import BAR_TYPES
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/progress_bars.py", line 12, in <module>
    from pip._internal.utils.logging import get_indentation
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/utils/logging.py", line 9, in <module>
    import logging.handlers
  File "/usr/lib/python3.7/logging/handlers.py", line 28, in <module>
    import queue
  File "/omd/sites/OMD_SITENAME/lib/python/future-0.16.0-py2.7.egg/queue/__init__.py", line 8, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.

OMD[omd_papy@papy-vps]:~$ ls -la /usr/local/bin/pip*
-rwxr-xr-x 1 root root 223 Jun 15 19:34 /usr/local/bin/pip*
-rwxr-xr-x 1 root root 223 Jun 15 19:34 /usr/local/bin/pip2*
-rwxr-xr-x 1 root root 223 Jun 15 19:34 /usr/local/bin/pip2.7*
-rwxr-xr-x 1 root root 223 Jun 15 15:36 /usr/local/bin/pip3*
-rwxr-xr-x 1 root root 223 Jun 15 15:36 /usr/local/bin/pip3.7*

pip -V
pip 20.1.1 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)
```

**Comment by datamuc** [comment]
The OMD_SITE has the  PYTHONPATH environment variable set, and OMD < 4 uses python 2 by default, so if you want to use python3 you have to unset PYTHONPATH (in a wrapper script for example), or change the shebang to `#!/usr/bin/python3 -E`

**Comment by hallux4** [comment]
Problem solved: The shebang thing did the trick.
A big thanks to you for the quality and rapidity of your answer !
