### ISSUE TITLE
Grafana API not able to communicate with Dashboard on SUSE Linux Enterprise Server 15 SP4

### ISSUE THREAD

**Issue by Xathviar** [ConSol/omd#144]
Hello, 

After installing OMD on a Suse Enterprise Server 15 SP4 I ran into the following issue when trying to look at dashboards from grafana. 
![issue](https://user-images.githubusercontent.com/41727154/207884941-d4820d6f-de58-41aa-9ffb-c67cc10c2efa.png)

And this is the error that is displayed on the dashboard.
![image](https://user-images.githubusercontent.com/41727154/207888155-4e3173cd-e29b-4dfd-b14a-c76900e6c9a0.png)

 It looks like Grafana can't reach it's API because of the Apache Configuration.  I am unfortunately not sure how to troubleshoot this. The steps that I already tried were trying to change the grafana.conf file inside of etc/apache/conf.d by creating a new Location: 
 
```apache
<Location /monitoring/grafana/api/live/ws>
      #Deal with websocket for live updates
      ProxyPreserveHost On
      ProxyPass ws://<host-name>/monitoring/grafana/api/live/ws
      ProxyPassReverse ws://<host-name>/monitoring/grafana/api/live/ws
</Location>
```
This didn't fix the error in the debug console. 

I am still able to create a custom Dashboard in Grafana and have it show me data from omd: 
![image](https://user-images.githubusercontent.com/41727154/207886509-c145027d-4531-4947-828a-775e536a9dc0.png)

After investigating the apache error_log the following log can be seen: 
```
[Thu Dec 15 15:31:31.640868 2022] [fcgid:warn] [pid 5155] [client 10.252.207.121:39074] mod_fcgid: stderr: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function {closure}(), 4 passed and exactly 5 expected in /opt/omd/versions/5.00-labs-edition/share/histou/index.php:16, referer: https://<host-name>/monitoring/grafana/dashboard-solo/script/histou.js?host=<host-name>&service=ram_usage&theme=dark&annotations=true&panelId=1
[Thu Dec 15 15:31:31.640895 2022] [fcgid:warn] [pid 5155] [client 10.252.207.121:39074] mod_fcgid: stderr: Stack trace:, referer: https://<host-name>/monitoring/grafana/dashboard-solo/script/histou.js?host=<host-name>&service=ram_usage&theme=dark&annotations=true&panelId=1
[Thu Dec 15 15:31:31.640900 2022] [fcgid:warn] [pid 5155] [client 10.252.207.121:39074] mod_fcgid: stderr: #0 /opt/omd/versions/5.00-labs-edition/share/histou/histou/bootstrap.php(22): {closure}(), referer: https://<host-name>/monitoring/grafana/dashboard-solo/script/histou.js?host=<host-name>&service=ram_usage&theme=dark&annotations=true&panelId=1
[Thu Dec 15 15:31:31.640904 2022] [fcgid:warn] [pid 5155] [client 10.252.207.121:39074] mod_fcgid: stderr: #1 /opt/omd/versions/5.00-labs-edition/share/histou/histou/bootstrap.php(22): require_once(), referer: https://<host-name>/monitoring/grafana/dashboard-solo/script/histou.js?host=<host-name>&service=ram_usage&theme=dark&annotations=true&panelId=1
[Thu Dec 15 15:31:31.640907 2022] [fcgid:warn] [pid 5155] [client 10.252.207.121:39074] mod_fcgid: stderr: #2 /opt/omd/versions/5.00-labs-edition/share/histou/histou/grafana/dashboard/dashboardinfluxdb.php(22): histou_autoload(), referer: https://<host-name>/monitoring/grafana/dashboard-solo/script/histou.js?host=<host-name>&service=ram_usage&theme=dark&annotations=true&panelId=1
[Thu Dec 15 15:31:31.640910 2022] [fcgid:warn] [pid 5155] [client 10.252.207.121:39074] mod_fcgid: stderr: #3 /opt/omd/versions/5.00-labs-edition/share/histou/histou/bootstrap.php(22): require_once('...'), referer: https://<host-name>/monitoring/grafana/dashboard-solo/script/histou.js?host=<host-name>&service=ram_usage&theme=dark&annotations=true&panelId=1
[Thu Dec 15 15:31:31.640914 2022] [fcgid:warn] [pid 5155] [client 10.252.207.121:39074] mod_fcgid: stderr: #4 /opt/omd/versions/5.00-labs-edition/share/histou/histou/grafana/dashboard/dashboardfactory.php(31): histou_autoload(), referer: https://<host-name>/monitoring/grafana/dashboard-solo/script/histou.js?host=<host-name>&service=ram_usage&theme=dark&annotations=true&panelId=1
[Thu Dec 15 15:31:31.640918 2022] [fcgid:warn] [pid 5155] [client 10.252.207.121:39074] mod_fcgid: stderr: #5 /opt/omd/versions/5.00-labs-edition/share/histou/templates/default/default.php(54): histou\\grafana\\dashboard\\DashboardFactory::generateDashboard(), referer: https://<host-name>/monitoring/grafana/dashboard-solo/script/histou.js?host=<host-name>&service=ram_usage&theme=dark&annotations=true&panelId=1
[Thu Dec 15 15:31:31.640929 2022] [fcgid:warn] [pid 5155] [client 10.252.207.121:39074] mod_fcgid: stderr: #6 /opt/omd/versions/5.00-labs-edition/share/histou/histou/template/template.php(87): histou\\template\\Loader::{closure}(), referer: https://<host-name>/monitoring/grafana/dashboard-solo/script/histou.js?host=<host-name>&service=ram_usage&theme=dark&annotations=true&panelId=1
[Thu Dec 15 15:31:31.640932 2022] [fcgid:warn] [pid 5155] [client 10.252.207.121:39074] mod_fcgid: stderr: #7 /opt/omd/versions/5.00-labs-edition/share/histou/histou/template/template.php(87): Closure->__invoke(), referer: https://<host-name>/monitoring/grafana/dashboard-solo/script/histou.js?host=<host-name>&service=ram_usage&theme=dark&annotations=true&panelId=1
[Thu Dec 15 15:31:31.640935 2022] [fcgid:warn] [pid 5155] [client 10.252.207.121:39074] mod_fcgid: stderr: #8 /opt/omd/versions/5.00-labs-edition/share/histou/index.php(147): histou\\template\\Template->generateDashboard(), referer: https://<host-name>/monitoring/grafana/dashboard-solo/script/histou.js?host=<host-name>&service=ram_usage&theme=dark&annotations=true&panelId=1
[Thu Dec 15 15:31:31.640938 2022] [fcgid:warn] [pid 5155] [client 10.252.207.121:39074] mod_fcgid: stderr: #9 {main}, referer: https://<host-name>/monitoring/grafana/dashboard-solo/script/histou.js?host=<host-name>&service=ram_usage&theme=dark&annotations=true&panelId=1
[Thu Dec 15 15:31:31.640941 2022] [fcgid:warn] [pid 5155] [client 10.252.207.121:39074] mod_fcgid: stderr:   thrown in /opt/omd/versions/5.00-labs-edition/share/histou/index.php on line 16, referer: https://<host-name>/monitoring/grafana/dashboard-solo/script/histou.js?host=<host-name>&service=ram_usage&theme=dark&annotations=true&panelId=1
```

I don't really know what's going on can  you help me troubleshoot it?

With best regards
Andreas

**Comment by sni** [comment]
Is this a custom dashboard? I don't think the `...live/ws` issue from the web console is related to this. I can see that error here as well and the dashboard just works fine.
The more promising lead is the histou error in the apache error log.
Try moving away custom templates from `etc/histou/templates/custom/` and see if the issue is gone. If so, you have to fix your templates.

**Comment by Xathviar** [comment]
Thank you for the quick Response. Unfortunately removing the custom templates didn't fix the issue.
